export default {
  frontend_url: process.env.FRONTEND_URL as string,
  port: process.env.PORT as string,
  db_url: process.env.DB_URL as string,
  log_level: "info",
  salt: 10,
  forgot_password_token_secret: process.env.FORGOT_PASSWORD_TOKEN_SECRET,
  access_token_public_key: process.env.ACCESS_TOKEN_PUBLIC_KEY,
  access_token_private_key: process.env.ACCESS_TOKEN_PRIVATE_KEY,
  refresh_token_public_key: process.env.REFRESH_TOKEN_PUBLIC_KEY,
  refresh_token_private_key: process.env.REFRESH_TOKEN_PRIVATE_KEY,
  access_token_expiry: 1000 * 60 * 60,
  refresh_token_expiry: 1000 * 60 * 60 * 24 * 365,
  access_token_cookie_expiry: 1000 * 60 * 60 * 24 * 365,
  refresh_token_cookie_expiry: 1000 * 60 * 60 * 24 * 365,
  google_client_id: process.env.GOOGLE_CLIENT_ID,
  google_client_secret: process.env.GOOGLE_CLIENT_SECRET,
  google_token_uri: process.env.GOOGLE_TOKEN_URI,
  redirect_uri: process.env.REDIRECT_URI,
  cloudinary_cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  cloudinary_api_key: process.env.CLOUDINARY_API_KEY,
  cloudinary_api_secret: process.env.CLOUDINARY_API_SECRET,
};
